### PR TITLE
Add mdast-flatten-listitem-paragraphs to readme.md

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks for your contributions, @staltz! Awesome things! What are you working on?

**Comment by staltz** [comment]
Thanks for merging! This other PR explains what I'm working on: https://github.com/rexxars/react-markdown/pull/199

**Comment by wooorm** [comment]
@staltz Sweet, interested to see where this goes, and let me know if you have questions re unified/remark/mdast/etc!

Oh and as an aside: stuff that can be passed to `unified().use()` is typically called `remark-` (or `unified-`), instead of `mdast-`. Maybe you already knew, and it’s not a problem for these little mdast utilities, but if you’d like to wrap them all into one plugin I suggest using `remark-` as a prefix!

**Comment by staltz** [comment]
Thanks for the tips!

**Pull request merged**
